name: MacOS C++ make-specs
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
      test_command:
        description: "Extra Test Command"
        type: string
        required: false
        default: python3 waf --run_tests
jobs:
  MacOS-mkspecs:
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: ARM64
            os: macOS
            name: Apple LLVM 12.0 64-bit (ARM)
          - arch: x64
            os: macOS
            name: Apple LLVM 12.0 64-bit (x86)
    runs-on: [self-hosted, "${{ matrix.config.os }}", "${{ matrix.config.arch }}", builder]
    name: ${{ matrix.config.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          GIT_SSH_COMMAND: "ssh"
          EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: python3 waf configure --git_protocol=git@ ${{ env.EXTRA_RESOLVE_OPTIONS }}
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        env:
          TEST_COMMAND: ${{ inputs.test_command }}
        run: ${{ env.TEST_COMMAND }}
