name: MacOS C++ make-specs
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
      test_command:
        description: "Extra Test Command"
        type: string
        required: false
        default: python3 waf --run_tests
jobs:
  MacOS-mkspecs:
    strategy:
      fail-fast: false
      matrix:
        config:
          - cxx_mkspec: cxx_apple_llvm120_x64
            name: Apple LLVM 12.0 64-bit
    runs-on: [self-hosted, "${{ matrix.config.cxx_mkspec }}"]
    name: ${{ matrix.config.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          GIT_SSH_COMMAND: "ssh"
          EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
        run: python3 waf configure --git_protocol=git@ --cxx_mkspec=${{ matrix.config.cxx_mkspec }} ${{ env.EXTRA_RESOLVE_OPTIONS }}
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        env:
          TEST_COMMAND: ${{ inputs.test_command }}
        run: ${{ env.TEST_COMMAND }}